import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f7',
        'surface-dim': '#f4d2cf',
        'surface-bright': '#fff8f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff0ee',
        'surface-container': '#ffe9e6',
        'surface-container-high': '#ffe2de',
        'surface-container-highest': '#fddbd7',
        'on-surface': '#291715',
        'on-surface-variant': '#5d3f3c',
        'inverse-surface': '#402b29',
        'inverse-on-surface': '#ffedea',
        outline: '#926f6b',
        'outline-variant': '#e7bdb8',
        'surface-tint': '#c00014',
        primary: '#ba0013',
        'on-primary': '#ffffff',
        'primary-container': '#e31e24',
        'on-primary-container': '#fffafa',
        'inverse-primary': '#ffb4ab',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e4e2e1',
        'on-secondary-container': '#656464',
        tertiary: '#006190',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007bb5',
        'on-tertiary-container': '#fbfcff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ab',
        'on-primary-fixed': '#410002',
        'on-primary-fixed-variant': '#93000d',
        'secondary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#c8c6c6',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        'tertiary-fixed': '#cbe6ff',
        'tertiary-fixed-dim': '#8ecdff',
        'on-tertiary-fixed': '#001e30',
        'on-tertiary-fixed-variant': '#004b71',
        background: '#fff8f7',
        'on-background': '#291715',
        'surface-variant': '#fddbd7',
      },
      fontFamily: {
        sans: ['var(--font-manrope)', 'sans-serif'],
        display: ['var(--font-oswald)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
      },
    },
  },
  plugins: [],
}

export default config;
